name: Build Docker images
on:
  repository_dispatch:
    types: [php-images-built]
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 7.2, 7.3, 7.4, 8.0 ]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 100

      - name: Determine latest released version
        id: latest_version
        uses: flownative/action-git-latest-release@master

      - name: Determine latest built PHP ${{ matrix.php }} version
        id: latest_php_version
        uses: flownative/action-docker-get-label@master
        with:
          image: europe-docker.pkg.dev/flownative/docker/php:${{ matrix.php }}
          label: org.label-schema.version
          registry: europe-docker.pkg.dev/flownative/docker
          username: '_json_key'
          password: ${{ secrets.GOOGLE_ARTIFACTS_PASSWORD_DOCKER }}

      - name: Build Docker image
        id: build_image
        uses: flownative/action-docker-build@v1
        with:
          tag_ref: ${{ steps.latest_version.outputs.tag }}
          image_name: flownative/docker/beach-php
          image_tag: ${{ steps.latest_php_version.outputs.value }}
          git_repository_url: https://europe-docker.pkg.dev/
          git_sha: ${{ github.sha }}
          registry_password: ${{ secrets.FLOWNATIVE_BOT_TOKEN }}


          target_image_name: europe-docker.pkg.dev/flownative/docker/beach-php
          target_registry_username: '_json_key'
          target_registry_password: ${{ secrets.GOOGLE_ARTIFACTS_PASSWORD_DOCKER }}
          target_registry_endpoint: https://europe-docker.pkg.dev

      - name: Tag semver releases
        uses: flownative/action-docker-publish-semver@v1
        with:
          tag_ref: ${{ steps.build_image.outputs.image_tag }}
          tag_latest: 'no'

          source_image_name: docker.pkg.github.com/flownative/docker-beach-php/beach-php
          source_registry_username: github
          source_registry_password: ${{ secrets.FLOWNATIVE_BOT_TOKEN }}
          source_registry_endpoint: https://docker.pkg.github.com/v2/

          target_image_name: docker.pkg.github.com/flownative/docker-beach-php/beach-php
          target_registry_username: github
          target_registry_password: ${{ secrets.FLOWNATIVE_BOT_TOKEN }}
          target_registry_endpoint: https://docker.pkg.github.com/v2/

  announce:
    runs-on: ubuntu-latest
    needs: buil
    steps:
      - name: Dispatch to beach-php-k8s
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.FLOWNATIVE_BOT_TOKEN }}
          repository: flownative/docker-beach-php-k8s
          event-type: beach-php-images-built
          client-payload: '{"image_name": "flownative/docker-php/beach-php"}'
